### ISSUE TITLE
oro/platform 4.1.4 requires ext-pcntl

### ISSUE THREAD

**Issue by vpietri-tbd** [kiboko-labs/docker-images#6] opened 2020-06-05 09:31 UTC
Hi,

The php extension **ext-pcntl** seems to be missing in the following images
kiboko/php:7.3-cli-orocommerce-ce-4.1-mysql
kiboko/php:7.4-cli-orocommerce-ce-4.1-mysql

Got error
  ```
Problem 1
    - oro/platform 4.1.4 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.
    - oro/platform 4.1.4 requires ext-pcntl * -> the requested PHP extension pcntl is missing from your system.
    - Installation request for oro/platform 4.1.4 -> satisfiable by oro/platform[4.1.4].
```
Thanks for your works.

**Comment by gplanchat** [comment] 2020-06-25 08:23
Hello @vpietri-tbd, thanks for your report.

I am checking this, it should be fixed today.

**Comment by gplanchat** [comment] 2020-06-25 10:15
@vpietri-tbd I cannot reproduce your issue, it seems it has been fixed a few weeks ago already.

Could you make a `docker pull` for both images ?

My checks :

```
gplanchat$ docker run --rm -ti kiboko/php:7.3-cli-orocommerce-ce-4.1-mysql php -m | grep pcntl
pcntl
gplanchat$ docker run --rm -ti kiboko/php:7.4-cli-orocommerce-ce-4.1-mysql php -m | grep pcntl
pcntl
```

**Comment by gplanchat** [comment] 2020-06-29 12:45
I am marking this issue as fixed.

Feel free to reopen if needed.

**Closed as completed by gplanchat** 2020-06-29 12:45 UTC
